// Export utilities - PDF and HTML generation

export async function exportToPDF(elementId: string, filename: string = 'climatwin-report') {
  try {
    const html2canvas = (await import('html2canvas')).default;
    const { jsPDF } = await import('jspdf');

    const element = document.getElementById(elementId);
    if (!element) {
      console.error('Export element not found:', elementId);
      return;
    }

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#FFFFFF',
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;
    const imgHeight = (canvas.height * contentWidth) / canvas.width;

    // Header
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('ClimaTwin India', margin, 15);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100);
    pdf.text('AI-Powered Digital Twin of India\'s Climate | ISRO Challenge PS-5', margin, 22);
    pdf.setDrawColor(0, 180, 220);
    pdf.setLineWidth(0.5);
    pdf.line(margin, 25, pageWidth - margin, 25);

    // Content
    let yOffset = 30;
    let remainingHeight = imgHeight;
    let sourceY = 0;

    while (remainingHeight > 0) {
      const availableHeight = pageHeight - yOffset - 15;
      const sliceHeight = Math.min(availableHeight, remainingHeight);
      const sliceCanvas = document.createElement('canvas');
      sliceCanvas.width = canvas.width;
      sliceCanvas.height = (sliceHeight / contentWidth) * canvas.width;
      const ctx = sliceCanvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(canvas, 0, sourceY * (canvas.width / contentWidth), canvas.width, sliceCanvas.height, 0, 0, sliceCanvas.width, sliceCanvas.height);
        pdf.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', margin, yOffset, contentWidth, sliceHeight);
      }
      remainingHeight -= sliceHeight;
      sourceY += sliceHeight;

      if (remainingHeight > 0) {
        pdf.addPage();
        yOffset = 15;
      }
    }

    // Footer on each page
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(7);
      pdf.setTextColor(150);
      pdf.text(`ClimaTwin India | AI Digital Twin | ISRO Challenge PS-5`, margin, pageHeight - 8);
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 25, pageHeight - 8);
      pdf.text(`Generated: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`, pageWidth / 2 - 20, pageHeight - 8);
    }

    pdf.save(`${filename}.pdf`);
  } catch (err) {
    console.error('PDF export failed:', err);
    alert('PDF export failed. Please try again.');
  }
}

export function exportToHTML(elementId: string, title: string = 'ClimaTwin Report') {
  const element = document.getElementById(elementId);
  if (!element) return;

  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - ClimaTwin India</title>
  <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Inter', sans-serif;
      background: #0a0a1a;
      color: #E2E8F0;
      margin: 0;
      padding: 2rem;
    }
    .header {
      text-align: center;
      padding: 2rem;
      border-bottom: 1px solid rgba(0,212,255,0.3);
      margin-bottom: 2rem;
    }
    .header h1 {
      font-family: 'Orbitron', monospace;
      color: #00D4FF;
      font-size: 2rem;
      letter-spacing: 0.3em;
    }
    .header p { color: #94A3B8; font-size: 0.9rem; }
    .content { max-width: 1200px; margin: 0 auto; }
    .footer {
      text-align: center;
      padding: 2rem;
      color: #64748B;
      font-size: 0.75rem;
      border-top: 1px solid rgba(0,212,255,0.2);
      margin-top: 2rem;
    }
    .watermark {
      position: fixed;
      bottom: 10px;
      right: 10px;
      font-family: 'Orbitron', monospace;
      font-size: 0.6rem;
      color: rgba(0,212,255,0.3);
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>CLIMATWIN INDIA</h1>
    <p>${title} | Generated ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
  </div>
  <div class="content">
    ${element.innerHTML}
  </div>
  <div class="footer">
    <p>ClimaTwin India | AI-Powered Digital Twin | ISRO Stoxra Hackathon 2026 | Problem Statement 5</p>
  </div>
  <div class="watermark">Generated by ClimaTwin India</div>
</body>
</html>`;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.toLowerCase().replace(/\s+/g, '-')}-report.html`;
  a.click();
  URL.revokeObjectURL(url);
}
