'use client';

import { useMode } from '@/lib/mode-context';

const REPORT_TEMPLATES = [
  { name: 'Daily Climate Bulletin', description: 'Comprehensive all-India climate data for today', icon: '📋', type: 'daily' },
  { name: 'State Climate Report', description: 'Detailed single-state climate analysis', icon: '🏛️', type: 'state' },
  { name: 'Extreme Events Summary', description: 'All current weather alerts and warnings', icon: '⚠️', type: 'extremes' },
  { name: 'AI Forecast Report', description: '7-day multi-model prediction summary', icon: '🤖', type: 'forecast' },
  { name: 'What-If Analysis Report', description: 'Climate scenario simulation results', icon: '🎛️', type: 'whatif' },
];

export default function ReportsPage() {
  const { isOperational } = useMode();

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">📄 Reports & Export</h1>
        <p className="page-subtitle">Generate professional reports in PDF (B&W) and HTML (interactive) formats</p>
      </div>

      {/* Report Templates */}
      <div className="grid-3" style={{ marginBottom: '1.5rem' }}>
        {REPORT_TEMPLATES.map((template, i) => (
          <div key={i} className="card card-glow" style={{ cursor: 'pointer' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
              <span style={{ fontSize: '1.5rem' }}>{template.icon}</span>
              <div>
                <h3 style={{ fontSize: '0.9rem', fontWeight: 600 }}>{template.name}</h3>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>{template.description}</p>
              </div>
            </div>
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button className="btn btn-primary btn-sm" style={{ flex: 1 }}>
                📄 PDF
              </button>
              <button className="btn btn-secondary btn-sm" style={{ flex: 1 }}>
                🌐 HTML
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Export Info */}
      <div className="grid-50-50" style={{ marginBottom: '1.5rem' }}>
        <div className="card">
          <h3 className="heading-sm" style={{ marginBottom: '0.75rem' }}>📄 PDF Export (Professional)</h3>
          <ul style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: 1.8, paddingLeft: '1rem' }}>
            <li>Clean black & white academic format</li>
            <li>ClimaTwin + ISRO logo in header</li>
            <li>Grayscale charts and data tables</li>
            <li>Page numbers, date stamps, margins (2.5cm)</li>
            <li>Executive summary + methodology note</li>
            <li>Footer: &quot;ClimaTwin India | ISRO Challenge PS-5&quot;</li>
          </ul>
        </div>
        <div className="card">
          <h3 className="heading-sm" style={{ marginBottom: '0.75rem' }}>🌐 HTML Export (Interactive)</h3>
          <ul style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: 1.8, paddingLeft: '1rem' }}>
            <li>Self-contained HTML file with embedded CSS</li>
            <li>Full color cosmic theme styling</li>
            <li>Interactive charts via Chart.js CDN</li>
            <li>All data embedded as JSON in script tags</li>
            <li>Print CSS for browser printing</li>
            <li>&quot;Generated by ClimaTwin India&quot; watermark</li>
          </ul>
        </div>
      </div>

      {/* Recent Exports */}
      <div className="card">
        <h3 className="heading-sm" style={{ marginBottom: '0.75rem' }}>Recent Export History</h3>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
          <thead>
            <tr>
              {['Report', 'Type', 'Generated', 'Size'].map(h => (
                <th key={h} style={{ textAlign: 'left', padding: '0.5rem', borderBottom: '1px solid var(--border-card)', fontSize: '0.65rem', color: 'var(--text-secondary)', textTransform: 'uppercase' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {[
              { name: 'Daily Climate Bulletin', type: 'PDF', date: 'Today, 14:30 IST', size: '2.4 MB' },
              { name: 'Maharashtra State Report', type: 'HTML', date: 'Today, 12:15 IST', size: '1.8 MB' },
              { name: 'Extreme Events Summary', type: 'PDF', date: 'Yesterday, 18:00 IST', size: '1.2 MB' },
              { name: 'AI Forecast (7-day)', type: 'PDF', date: 'Yesterday, 09:00 IST', size: '3.1 MB' },
            ].map((exp, i) => (
              <tr key={i}>
                <td style={{ padding: '0.5rem', borderBottom: '1px solid rgba(255,255,255,0.03)' }}>{exp.name}</td>
                <td style={{ padding: '0.5rem', borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                  <span className={`badge ${exp.type === 'PDF' ? 'badge-red' : 'badge-cyan'}`} style={{ fontSize: '0.55rem' }}>{exp.type}</span>
                </td>
                <td style={{ padding: '0.5rem', borderBottom: '1px solid rgba(255,255,255,0.03)', color: 'var(--text-secondary)' }}>{exp.date}</td>
                <td style={{ padding: '0.5rem', borderBottom: '1px solid rgba(255,255,255,0.03)' }} className="mono-value">{exp.size}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
